export const quotes = [
  "The secret of getting ahead is getting started. — Mark Twain",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Success is the sum of small efforts repeated day in and day out. — Robert Collier",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Dream big. Start small. Act now. — Robin Sharma",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "Action is the foundational key to all success. — Pablo Picasso",
  "Small daily improvements over time lead to stunning results. — Robin Sharma",
  "Your limitation—it's only your imagination.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Success doesn't just find you. You have to go out and get it.",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  "Believe in yourself and all that you are. — Christian D. Larson",
  "The only way to do great work is to love what you do. — Steve Jobs",
  "If you can dream it, you can do it. — Walt Disney",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
  "What you get by achieving your goals is not as important as what you become. — Zig Ziglar",
  "The future depends on what you do today. — Mahatma Gandhi",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "Quality is not an act, it is a habit. — Aristotle",
  "Well done is better than well said. — Benjamin Franklin",
  "Either you run the day, or the day runs you. — Jim Rohn",
  "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
]
